# Generated by Django 3.0.6 on 2020-05-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20151209_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruserprofile',
            name='url',
            field=models.URLField(blank=True, verbose_name='profile'),
        ),
    ]
